#!/usr/bin/expect -f
set ip [lindex $argv 0]
set password [lindex $argv 1]
set timeout 30
spawn ssh -F /dev/null $ip
expect {
        "*passphrase*" {
                send "$password\r"
        }
}

interact
